# Generated by Django 3.2.4 on 2021-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default='1111111', max_length=255, verbose_name='设备编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '未借出'), (1, '借用审核中'), (2, '已借出')], default=0, verbose_name='设备状态'),
        ),
    ]
