# Generated by Django 3.2.4 on 2021-06-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210623_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='comments',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='设备编号'),
        ),
    ]
