# Generated by Django 3.2.4 on 2021-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20210623_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
