# Generated by Django 3.2.4 on 2021-07-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='位置编号')),
                ('name', models.CharField(max_length=55, verbose_name='位置')),
            ],
            options={
                'verbose_name': '位置表',
                'verbose_name_plural': '位置表',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.location'),
        ),
    ]
