# Generated by Django 3.2.4 on 2021-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=255, verbose_name='借用人')),
                ('state', models.SmallIntegerField(choices=[(0, '申请借用'), (1, '申请归还')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '审批表',
                'verbose_name_plural': '审批表',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('username', models.CharField(max_length=255, verbose_name='借用人')),
                ('operation', models.SmallIntegerField(choices=[(0, '借出'), (1, '归还')], verbose_name='操作')),
                ('device', models.CharField(max_length=255, verbose_name='设备')),
                ('approver', models.CharField(max_length=255, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '记录表',
                'verbose_name_plural': '记录表',
            },
        ),
    ]
