# Generated by Django 3.2.4 on 2021-06-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.device'),
        ),
        migrations.AddField(
            model_name='approve',
            name='operation',
            field=models.SmallIntegerField(choices=[(0, '申请借用'), (1, '申请归还')], default=1, verbose_name='操作'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approve',
            name='state',
            field=models.BooleanField(verbose_name='审批状态'),
        ),
    ]
