# Generated by Django 3.2.4 on 2021-06-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20210623_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='state',
            field=models.BooleanField(default=False, verbose_name='审批状态'),
        ),
    ]
