# Generated by Django 3.2.4 on 2021-06-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_approve_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approve',
            options={'ordering': ['created_time'], 'verbose_name': '审批表', 'verbose_name_plural': '审批表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['created_time'], 'verbose_name': '记录表', 'verbose_name_plural': '记录表'},
        ),
    ]
