# Generated by Django 3.2.4 on 2021-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20210623_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='deviceId',
            field=models.CharField(default=1111, max_length=255, verbose_name='设备序列号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approve',
            name='deviceName',
            field=models.CharField(default=1111, max_length=255, verbose_name='设备名称'),
            preserve_default=False,
        ),
    ]
