# Generated by Django 3.2.4 on 2021-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_approve_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deviceId',
            field=models.CharField(default=1, max_length=255, verbose_name='设备序列号'),
            preserve_default=False,
        ),
    ]
