# Generated by Django 3.2.4 on 2021-06-26 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_device_comments'),
        ('record', '0008_record_deviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='deviceId',
        ),
        migrations.AlterField(
            model_name='record',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.device'),
        ),
    ]
