# Generated by Django 3.2.4 on 2021-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20210626_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve',
            name='deviceId',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='deviceName',
        ),
    ]
