# Generated by Django 3.2.4 on 2021-07-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_device_location'),
        ('record', '0010_auto_20210626_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device.location', verbose_name='位置'),
        ),
    ]
