# Generated by Django 3.2.4 on 2021-12-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_options'),
        ('record', '0011_approve_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
    ]
