# Generated by Django 3.2.4 on 2021-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210623_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=255, verbose_name='用户姓名')),
                ('username', models.CharField(max_length=255, verbose_name='学号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户注册表',
                'verbose_name_plural': '用户注册表',
            },
        ),
    ]
