# Generated by Django 3.2.4 on 2021-07-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='classes',
            field=models.SmallIntegerField(blank=True, choices=[(0, '图片')], default=0, null=True, verbose_name='类型'),
        ),
    ]
